# -*- Mode: Python -*-

Import('fbsd_env')

for interface in [['device', 'kern'], ['bus', 'kern'], ['pci', 'dev/pci']]:
    fbsd_env.Command(['%s_if.h' % interface[0], '%s_if.c' % interface[0]],
                     ['#contrib/freebsd/sys/tools/makeobjops.awk',
                      '#contrib/freebsd/sys/%s/%s_if.m'  % (interface[1], interface[0])],
                     "nawk -f ${SOURCES[0].abspath} ${SOURCES[1].abspath} -c -h",
                     chdir=True)

# unimplemented.inc was generated on a FreeBSD 10-STABLE box with:
# nm -g /boot/kernel/kernel | grep ' [tT] ' | sed -E 's/^.* [tT] (.*)$/FN_UNIMPL(\1);/' > unimplemented.inc

fbsd_env.SharedLibrary('fbsd_common', ['unimplemented.c',
                                       'device_if.c',
                                       'bus_if.c',
                                       'pci_if.c',
                                       ])

# EOF
